import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'

const Home: NextPage = () => {
  const router = useRouter()
  return (
    <div>
      <Head>
        <title>홈</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      안녕 안녕
      <button onClick={() => router.push('/step1')}>step 1 으로 가기</button>
    </div>
  )
}

export default Home
