import { RootState } from '@redux/store'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useSelector } from 'react-redux'

const Home: NextPage = () => {
  const router = useRouter()
  const image = useSelector((state: RootState) => state.image)

  console.log(image)

  return (
    <div>
      <Head>
        <title>홈</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      안녕 안녕
      <button onClick={() => router.push('/step1')}>step 1 으로 가기</button>
    </div>
  )
}

export default Home
